ALTER TABLE users
    ADD COLUMN account_type VARCHAR(50) NOT NULL DEFAULT 'PERSONAL',
ADD COLUMN account_status VARCHAR(50) NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN currency VARCHAR(10) NOT NULL DEFAULT 'ZAR',
ADD COLUMN monthly_budget_cycle_day INTEGER NOT NULL DEFAULT 1,
ADD COLUMN notifications_enabled BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN deletion_requested BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN deletion_requested_at TIMESTAMP NULL;