micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:3000
            - https://your-frontend-domain.vercel.app
          allowed-methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization
  security:
    enabled: true
    token:
      jwt:
        enabled: true
        generator:
          access-token:
            expiration: 3600
        signatures:
          secret:
            generator:
              secret: ${JWT_SECRET}

datasources:
  default:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:6543/moneymap`}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME:moneymap}
    password: ${DATABASE_PASSWORD:moneymap}
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

flyway:
  datasources:
    default:
      enabled: true