micronaut:
  server:
    cors:
      enabled: true
      configurations:
        web:
          allowed-origins:
            - http://localhost:3000
          allowed-methods:
            - GET
            - POST
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
          allowed-headers:
            - Content-Type
            - Authorization

datasources:
  default:
    url: ${DATABASE_URL:`jdbc:postgresql://localhost:6543/moneymap`}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USERNAME:moneymap}
    password: ${DATABASE_PASSWORD:moneymap}
    dialect: POSTGRES

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

flyway:
  datasources:
    default:
      enabled: true